PLUGIN_NAME=		devicemonitor
PLUGIN_VERSION=		2.3
PLUGIN_COMMENT=		Device Monitor - network device tracking
PLUGIN_MAINTAINER=	maxysoft
PLUGIN_WWW=		https://github.com/maxysoft/opnsense-devicemonitor
PLUGIN_DEPENDS=		python3

.include "../../Mk/plugins.mk"
